name: Build MinGW
on:
  push:
    tags:
      - "*"
jobs:
  mingw-w64:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make -f Makefile.mingw.mk
      - name: Upload library
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/mingw/libbismite-mingw.tgz
          asset_name: libbismite-mingw-${{github.ref_name}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload samples
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: build/mingw/libbismite-mingw-samples.tgz
          asset_name: libbismite-mingw-samples-${{github.ref_name}}.tgz
          overwrite: true
