name: Build MinGW
on:
  push:
    tags:
      - '*'
jobs:
  mingw-w64:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make -f Makefile.mingw.mk
      - name: Upload library
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/x86_64-w64-mingw32/libbismite-x86_64-w64-mingw32.tgz
          asset_name: libbismite-x86_64-w64-mingw32-${{github.ref_name}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload samples
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/x86_64-w64-mingw32/libbismite-x86_64-w64-mingw32-samples.tgz
          asset_name: libbismite-x86_64-w64-mingw32-samples-${{github.ref_name}}.tgz
          overwrite: true
