name: Build Emscripten
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.24
          actions-cache-folder: 'emsdk-cache'
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: make -f Makefile.emscripten.mk
      - name: Upload library archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/emscripten/libbismite-emscripten.tgz
          asset_name: libbismite-emscripten-${{github.ref_name}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload samples archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/emscripten/libbismite-emscripten-samples.tgz
          asset_name: libbismite-emscripten-samples-${{github.ref_name}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
