name: Build Linux
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install clang libgl-dev libyaml-dev
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make -f Makefile.linux.mk
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/libbismite-linux.tgz
          asset_name: libbismite-linux-${{github.ref_name}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload samples
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: build/linux/libbismite-linux-samples.tgz
          asset_name: libbismite-linux-samples-${{github.ref_name}}.tgz
          overwrite: true
