name: Build macOS
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-10.15
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: make -f Makefile.macos.mk release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/macos/libbismite.tgz
          asset_name: libbismite.tgz
          tag: ${{ github.ref }}
          overwrite: true
