name: Build macOS
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make -f Makefile.macos.mk
      - name: Upload library
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/macos/libbismite-macos.tgz
          asset_name: libbismite-macos-${{github.ref_name}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload samples
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: build/macos/libbismite-macos-samples.tgz
          asset_name: libbismite-macos-samples-${{github.ref_name}}.tgz
          overwrite: true
