name: Build
on: [push]
env:
  EM_VERSION: 3.1.71
  EM_CACHE_FOLDER: "emsdk-cache"
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: "ubuntu-24.04", target: "mingw" }
          - { os: "ubuntu-24.04", target: "linux" }
          - { os: "ubuntu-24.04", target: "emscripten" }
          - { os: "macos-14", target: "macos" }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies for mingw
        if: ${{ matrix.target == 'mingw' }}
        run: sudo apt-get install mingw-w64
      - name: Install dependencies for linux
        if: ${{ matrix.target == 'linux' }}
        run: |
          sudo apt update
          sudo apt install clang libgl-dev
      - uses: actions/cache@v4
        if: ${{ matrix.target == 'emscripten' }}
        id: cache-system-libraries
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        if: ${{ matrix.target == 'emscripten' }}
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: make -j2 -f Makefile.${{matrix.target}}.mk
      - uses: actions/upload-artifact@v4
        with:
          name: libbismite-${{matrix.target}}-${{github.sha}}.tgz
          path: build/${{matrix.target}}/libbismite-${{matrix.target}}.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: libbismite-${{matrix.target}}-samples-${{github.sha}}.tgz
          path: build/${{matrix.target}}/libbismite-${{matrix.target}}-samples.tgz
      - uses: svenstaro/upload-release-action@2.9.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          file: build/${{matrix.target}}/libbismite-${{matrix.target}}.tgz
          asset_name: libbismite-${{matrix.target}}-${{github.ref_name}}.tgz
          overwrite: true
      - uses: svenstaro/upload-release-action@2.9.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          file: build/${{matrix.target}}/libbismite-${{matrix.target}}-samples.tgz
          asset_name: libbismite-${{matrix.target}}-samples-${{github.ref_name}}.tgz
          overwrite: true
