name: Build Emscripten no-simd
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: mymindstorm/setup-emsdk@v9
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: make -f Makefile.emscripten-nosimd.mk release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/emscripten-nosimd/libbismite-emscripten-nosimd.tgz
          asset_name: libbismite-emscripten-nosimd.tgz
          tag: ${{ github.ref }}
          overwrite: true
