name: Build Linux
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libyaml-dev clang
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: make -f Makefile.linux.mk release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/libbismite-linux.tgz
          asset_name: build/linux/libbismite-linux.tgz
          tag: ${{ github.ref }}
          overwrite: true
