name: Build Emscripten
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: mymindstorm/setup-emsdk@v9
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: make -f Makefile.emscripten.mk release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/emscripten/libbismite-emscripten.tgz
          asset_name: build/emscripten/libbismite-emscripten.tgz
          tag: ${{ github.ref }}
          overwrite: true
